// el make file bykun gowaha nha tinclude files bta3t el standard lib w ydefhum w ygeb kol el source file 
// include el static w el dynamic libaray 
build:
		g++ ./main.cpp -o ./main.exe

clean:
		rm ./main.exe

run:
		./main.exe
